# Site settings
title: Amy and Amir's Wedding
description: > # this means to ignore newlines until "baseurl:"
    We would like to invite you to celebrate with us at our Wedding!
url: "http://yourdomain.com"
baseurl: ""
logo: <i class="material-icons">face</i>Amy and Amir's Wedding
paginate: 5
paginate_path: "/page:num/"
owner:
    email:
    facebook:
        show: false
        name: ""
        url: ""
    github:
        show: false
        username: ""
    twitter:
        show: false
        username: ""
    disqus:
        show: false
        username: ""
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: true
gems:
    - jekyll-feed
    - jekyll-paginate
    - redcarpet